version: "3.8"

services:
  athena_web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/shekshuev/athena:latest
    container_name: athena_web
    restart: always
    env_file:
      - .env
    ports:
      - "${WEB_PORT_EXTERNAL:-80}:4000"
    depends_on:
      - postgres
      - minio
    networks:
      - athena-network

  postgres:
    image: postgres:15-alpine
    container_name: athena_prod_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - athena-network

  minio:
    image: minio/minio
    container_name: athena_prod_minio
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - .env
    volumes:
      - minio_prod_data:/data
    ports:
      - "${MINIO_PORT_EXTERNAL:-9000}:9000"
      - "${MINIO_CONSOLE_PORT_EXTERNAL:-9001}:9001"
    networks:
      - athena-network

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    networks:
      - athena-network
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD); do echo 'Waiting for MinIO...'; sleep 1; done;
      /usr/bin/mc mb myminio/$$MINIO_BUCKET || true;
      /usr/bin/mc anonymous set public myminio/$$MINIO_BUCKET;
      exit 0;
      "

networks:
  athena-network:
    driver: bridge

volumes:
  postgres_prod_data:
  minio_prod_data:
