ARG ELIXIR_VERSION=1.19.5
ARG OTP_VERSION=27.3.4.10
ARG DEBIAN_VERSION=bookworm-20260610-slim

ARG BUILDER_IMAGE="docker.io/hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="docker.io/debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS builder
ARG COMMIT_SHA
ENV COMMIT_SHA=$COMMIT_SHA

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential git curl ca-certificates \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y --no-install-recommends nodejs \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN mix local.hex --force && mix local.rebar --force
ENV MIX_ENV="prod"

COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

COPY assets/package.json assets/package-lock.json* ./assets/
RUN npm install --prefix assets --progress=false --silent

COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY assets/postcss.config.js ./assets/
RUN mix assets.setup
COPY priv priv
COPY lib lib
RUN mix compile

COPY assets assets
RUN mix assets.deploy

COPY config/runtime.exs config/
COPY rel rel
RUN mix release

FROM ${RUNNER_IMAGE} AS final

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 openssl libncurses6 locales ca-certificates \
    python3 g++ \
    git make gcc libcap-dev pkg-config libseccomp-dev libsystemd-dev \
  && rm -rf /var/lib/apt/lists/*

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN git clone https://github.com/ioi/isolate.git /tmp/isolate \
  && cd /tmp/isolate \
  && make isolate \
  && make install \
  && rm -rf /tmp/isolate \
  && ln -s /usr/local/bin/isolate /usr/bin/isolate

RUN useradd -r -s /bin/false isolate \
  && echo "isolate:100000:65536" >> /etc/subuid \
  && echo "isolate:100000:65536" >> /etc/subgid \
  && echo "root:100000:65536" >> /etc/subuid \
  && echo "root:100000:65536" >> /etc/subgid

RUN mkdir -p /run/isolate/locks /var/local/lib/isolate \
  && chmod 777 /var/local/lib/isolate

WORKDIR "/app"
ENV MIX_ENV="prod"

COPY --from=builder /app/_build/${MIX_ENV}/rel/athena ./

CMD ["/app/bin/entrypoint"]