version: "3.8"

services:
  athena_web:
    image: ghcr.io/shekshuev/athena-ex-web:latest
    container_name: athena_web
    restart: always
    network_mode: "host"
    env_file:
      - .env
    environment:
      - SERVER_ROLE=default
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=web@127.0.0.1
      - RELEASE_COOKIE=${RELEASE_COOKIE}
    depends_on:
      - postgres
      - minio

  athena_runner:
    image: ghcr.io/shekshuev/athena-ex-runner:latest
    container_name: athena_runner
    privileged: true
    restart: always
    network_mode: "host"
    env_file:
      - .env
    environment:
      - SERVER_ROLE=runner
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=runner1@127.0.0.1
      - RELEASE_COOKIE=${RELEASE_COOKIE}
    depends_on:
      - athena_runner_pg

  athena_runner_pg:
    image: postgres:16-alpine
    container_name: athena_runner_pg_dev
    restart: "no"
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_RUNNER_PASSWORD}
      - POSTGRES_INITDB_ARGS=--nosync
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c log_statement=none -p 5433
    tmpfs:
      - /var/lib/postgresql/data:size=512m

  postgres:
    image: postgres:15-alpine
    container_name: athena_prod_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5432}:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: athena_prod_minio
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - .env
    volumes:
      - minio_prod_data:/data
    ports:
      - "${MINIO_PORT_EXTERNAL:-9000}:9000"
      - "${MINIO_CONSOLE_PORT_EXTERNAL:-9001}:9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://127.0.0.1:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD); do echo 'Waiting for MinIO...'; sleep 1; done;
      /usr/bin/mc mb myminio/$$MINIO_BUCKET || true;
      /usr/bin/mc anonymous set public myminio/$$MINIO_BUCKET;
      exit 0;
      "

volumes:
  postgres_prod_data:
  minio_prod_data:
