version: "3.8"

services:
  athena_runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: athena_runner_1
    restart: always
    privileged: true
    pid: "host"
    cgroup: "host"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    env_file:
      - .env
    environment:
      - SERVER_ROLE=runner
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=runner1@athena_runner
      - RELEASE_COOKIE=${RELEASE_COOKIE}
    networks:
      - athena-network
    depends_on:
      - athena_runner_pg

  athena_runner_pg:
    image: postgres:16-alpine
    container_name: athena_runner_pg_dev
    restart: "no"
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=runner_secret
      - POSTGRES_INITDB_ARGS=--nosync
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c log_statement=none -p 5433
    tmpfs:
      - /var/lib/postgresql/data:size=512m

networks:
  athena-network:
    external: true
